
#ifndef RSDIO_EXPORT_H
#define RSDIO_EXPORT_H

#define RSDIO_EXPORT
#define RSDIO_NO_EXPORT

#ifndef RSDIO_DEPRECATED
#  define RSDIO_DEPRECATED __declspec(deprecated)
#endif

#ifndef RSDIO_DEPRECATED_EXPORT
#  define RSDIO_DEPRECATED_EXPORT RSDIO_EXPORT RSDIO_DEPRECATED
#endif

#ifndef RSDIO_DEPRECATED_NO_EXPORT
#  define RSDIO_DEPRECATED_NO_EXPORT RSDIO_NO_EXPORT RSDIO_DEPRECATED
#endif

#endif /* RSDIO_EXPORT_H */
