class PoeState: ...

class RsPoe:
    def setXmlFile(self, filename: str) -> None: ...
    def getPortState(self, port: int) -> PoeState: ...
    def setPortState(self, port: int, state: PoeState) -> None: ...
    def getLastError(self) -> str: ...
    def version(self) -> str: ...
