
#ifndef RSPOE_EXPORT_H
#define RSPOE_EXPORT_H

#define RSPOE_EXPORT
#define RSPOE_NO_EXPORT

#ifndef RSPOE_DEPRECATED
#  define RSPOE_DEPRECATED __declspec(deprecated)
#endif

#ifndef RSPOE_DEPRECATED_EXPORT
#  define RSPOE_DEPRECATED_EXPORT RSPOE_EXPORT RSPOE_DEPRECATED
#endif

#ifndef RSPOE_DEPRECATED_NO_EXPORT
#  define RSPOE_DEPRECATED_NO_EXPORT RSPOE_NO_EXPORT RSPOE_DEPRECATED
#endif

#endif /* RSPOE_EXPORT_H */
